/**
 * tailwind.config.js — NEED Stitch Civic Cooperative design system.
 */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch Official Color Tokens (Dynamic Theme Variables)
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-dim': 'rgb(var(--color-surface-dim) / <alpha-value>)',
        'surface-bright': 'rgb(var(--color-surface-bright) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
        outline: 'rgb(var(--color-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value>)',
        'surface-tint': 'rgb(var(--color-surface-tint) / <alpha-value>)',
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--color-inverse-primary) / <alpha-value>)',
        secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
        'on-secondary': 'rgb(var(--color-on-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--color-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        tertiary: 'rgb(var(--color-tertiary) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--color-on-tertiary) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--color-on-tertiary-container) / <alpha-value>)',
        error: 'rgb(var(--color-error) / <alpha-value>)',
        'on-error': 'rgb(var(--color-on-error) / <alpha-value>)',
        'error-container': 'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--color-on-error-container) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--color-primary-fixed) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--color-primary-fixed-dim) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--color-on-primary-fixed) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--color-secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--color-secondary-fixed-dim) / <alpha-value>)',
        'on-secondary-fixed': 'rgb(var(--color-on-secondary-fixed) / <alpha-value>)',
        'on-secondary-fixed-variant': 'rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)',
        'tertiary-fixed': 'rgb(var(--color-tertiary-fixed) / <alpha-value>)',
        'tertiary-fixed-dim': 'rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)',
        'on-tertiary-fixed': 'rgb(var(--color-on-tertiary-fixed) / <alpha-value>)',
        'on-tertiary-fixed-variant': 'rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)',
        background: 'rgb(var(--color-surface) / <alpha-value>)',
        'on-background': 'rgb(var(--color-on-surface) / <alpha-value>)',
        'surface-variant': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',

        // Legacy compatibility aliases
        ink: {
          DEFAULT: '#131B2E',
          900: '#0F172A',
          800: '#131B2E',
          700: '#334155',
          600: '#475569',
        },
        brand: {
          50: '#E6F7F0',
          100: '#B8EBD7',
          200: '#8DDEC0',
          500: '#007A55',
          600: '#005F41',
          700: '#005137',
        },
        marigold: {
          50: '#FFF4DF',
          400: '#FFB95F',
          500: '#FEA619',
          600: '#855300',
        },
        verified: '#007A55',
        pending: '#C98A04',
        rejected: '#BA1A1A',
        paper: '#FAF8FF',
        line: '#BDC9C1',
        muted: '#64748B',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        mono: ['"Plus Jakarta Sans"', 'ui-monospace', 'monospace'],
        'display-lg': ['"Plus Jakarta Sans"'],
        'display-lg-mobile': ['"Plus Jakarta Sans"'],
        'headline-xl': ['"Plus Jakarta Sans"'],
        'headline-xl-mobile': ['"Plus Jakarta Sans"'],
        'headline-lg': ['"Plus Jakarta Sans"'],
        'headline-md': ['"Plus Jakarta Sans"'],
        'headline-sm': ['"Plus Jakarta Sans"'],
        'body-lg': ['"Plus Jakarta Sans"'],
        'body-md': ['"Plus Jakarta Sans"'],
        'body-sm': ['"Plus Jakarta Sans"'],
        'label-lg': ['"Plus Jakarta Sans"'],
        'label-md': ['"Plus Jakarta Sans"'],
        'label-caps': ['"Plus Jakarta Sans"'],
        'metric-val': ['"Plus Jakarta Sans"'],
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1440px',
        '3xl': '1920px',
      },
      // Semantic type scale. Sizes were originally tuned for a 1280px design
      // canvas; now that the container goes to 1440/1680/1840 the content-
      // bearing steps are a notch larger so text does not read as small print
      // on a big display. Caps/label steps stay small on purpose — they are
      // labels, not body copy.
      fontSize: {
        'display-lg': ['60px', { lineHeight: '66px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-lg-mobile': ['34px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-xl': ['42px', { lineHeight: '50px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-xl-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['19px', { lineHeight: '27px', fontWeight: '600' }],
        'body-lg': ['19px', { lineHeight: '30px', fontWeight: '400' }],
        'body-md': ['17px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['15px', { lineHeight: '22px', fontWeight: '600' }],
        'label-md': ['13.5px', { lineHeight: '19px', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'metric-val': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'container-max': '1440px',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgba(15, 23, 42, 0.04)',
        DEFAULT: '0 1px 3px 0 rgba(15, 23, 42, 0.06), 0 1px 2px -1px rgba(15, 23, 42, 0.04)',
        md: '0 4px 6px -1px rgba(15, 23, 42, 0.06), 0 2px 4px -2px rgba(15, 23, 42, 0.04)',
        lg: '0 10px 15px -3px rgba(15, 23, 42, 0.06), 0 4px 6px -4px rgba(15, 23, 42, 0.03)',
        xl: '0 20px 25px -5px rgba(15, 23, 42, 0.08), 0 8px 10px -6px rgba(15, 23, 42, 0.03)',
        card: '0 1px 3px 0 rgba(15, 23, 42, 0.04), 0 1px 2px -1px rgba(15, 23, 42, 0.02)',
        lift: '0 10px 15px -3px rgba(15, 23, 42, 0.06), 0 4px 6px -4px rgba(15, 23, 42, 0.03)',
      },
      // Kept in step with the .container-page ladder in index.css.
      maxWidth: {
        content: '1440px',
        'container-max': '1440px',
        'site-max': '1440px',
        prose: '46rem',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
      animation: {
        'fade-in': 'fade-in 180ms ease-out',
      },
    },
  },
  plugins: [],
}
